In [1]:
import numpy as np


ndarray-n dimensional array--very very useful

In [3]:
a=np.array([1,2,3,4])

In [4]:
type(a)

numpy.ndarray

In core python no concept of array...numpy is a library through which we can define array
there are many ways to define array in numpy itself....another module in Python which array concept is there is below:

In [8]:
import array as ar
ar.array('i',[1,2,3,4])

array('i', [1, 2, 3, 4])

In [9]:
a=np.array([1,2,'a',1.2])

In [10]:
a

array(['1', '2', 'a', '1.2'], dtype='<U11')

In [11]:
type(a)

numpy.ndarray

In [12]:
a1=np.array([1,2,3,4],ndmin=3)

In [13]:
a1

array([[[1, 2, 3, 4]]])

# Dimensions of array

In [15]:
a1=np.array([1,2,3,4],ndmin=0)
a1

array([1, 2, 3, 4])

In [16]:
a2=np.array([1,2,3,4],ndmin=1)
a2


array([1, 2, 3, 4])

In [18]:
a3=np.array([1,2,3,4],ndmin=2)
a3

array([[1, 2, 3, 4]])

In [20]:
a4=np.array([[1,2,3],[3,4,5]])
a4

array([[1, 2, 3],
       [3, 4, 5]])

In [23]:
type(a4)

numpy.ndarray

In [22]:
a5=np.array([[[1,2,3]],[[2,3,4]],[[5,6,7]]])
a5

array([[[1, 2, 3]],

       [[2, 3, 4]],

       [[5, 6, 7]]])