 #numerical python
library for array and matrix manipulation
previously there was for Matlab-framework for simulation tool-they have inherited all the functions and operations
later it was introduced in Python with name Numpy
array can have any kind of data-int/float/str/complex etc.
we can represent everything in array or matrices like images/objects etc.
dtype <U64' is unicode 64 character  only available in numpy -for diff kind of calculation
every library like tensorflow etc understands numpy
any model understand numpy
Ml/DL/NLP everywhere using numpy
available in anaconda installation
list- python core
numpy is liibrary

array vs asarray Vs asanyarray:
-----------------------------------------------
The function definitions are :

numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
and

numpy.asarray(a, dtype=None, order=None)

When you make numpy array using np.array than it would create a copy of the object array and would not reflect changes to the original array (with default parameters). On the other hand if you use np.asarray() than it would reflect changes to the original array.

-asanyarray convert input into array if input is given in form of non-array format but if iput is form of array then it wont do any conversion.


Deep copy Vs shallowcopy
---------------------------------------------

np.copy() will create diff location but same data- DEEP COPY-DIFF Location
y=x ==>swallow copy=> refers same location 















In [ ]:
import numpy as np 

# Numpy Array

In [ ]:
l=["dd",1,2]
np.array(l)

In [ ]:
np.array(["dd",1,2])

In [ ]:
a=np.array([1,2,3])
a

In [ ]:
type(a)

# Upcasting

In [ ]:
np.array([1,2,3.0])

In [ ]:
b=np.array([5,6.7,(5+7j),'s'])
b

In [ ]:
type(b)

In [ ]:
#complex datatype for array eles

In [ ]:
np.array([5,6,7], dtype=complex)

In [ ]:
#str type array ele

In [ ]:
np.array([4,5,6], dtype=str)

# Asarray

# asanyarray convert input into array if input is given in form of non-array format but if iput is form of array then it wont do any conversion.


In [ ]:
l=[1,2,3]  #list is non array form so asanyarray func converted into the array- check return type
a=np.asanyarray(l)
a

In [ ]:
type(a)

In [ ]:
m=np.matrix(l)  #matrix is subfom of array so asanyarray func didnt convert it into array- check return type
m

In [ ]:
b=np.asanyarray(m)
b

In [ ]:
type(b)

# now passing matrix in array function

In [ ]:
c=np.array(m)  #array func converted the matrix into array-- check return type
c

In [ ]:
type(c)

# now passing matrix into asarray func

In [ ]:
c=np.asarray(m)
c

In [ ]:
type(c)

In [ ]:
#np.asarray

In [ ]:
a1=np.asarray([4,5,6,7])
a1

In [ ]:
type(a1)

In [ ]:
a2=np.asarray([4,5,6,7], dtype=np.float16)

In [ ]:
type(a2)

# 2-D Array

In [ ]:
np.array([[2,3,4],[1,2]])

In [ ]:
np.array([[2,3,4],[1,2,3]])  #passing ltwo list as eles in array

# Multidimension Array -
we can change one dim array to ther dim

In [ ]:
np.array([1,2,3,4], ndmin=5)

In [ ]:
np.array([1,2,3,4], dtype=str)

# Data-type consisting of more than one element:

In [ ]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

In [ ]:
x[1][0]


In [ ]:
type(x)

In [ ]:
type(x[1][0])

# Matrix- subclass of array- any matrix can be converted into array -True
array is subclass of matrix-False

In [ ]:
issubclass(np.matrix,np.ndarray)

In [ ]:
issubclass(np.ndarray,np.matrix)

In [ ]:
a=np.array([[1,2],[3,4]])
a

Converting array into matrix

In [ ]:
m=np.mat(a)

In [ ]:
type(m)

# data is string and separated by semi colon ;

In [ ]:
b=np.mat('1,2;3,4')
b

In [ ]:
type(b)

# list into matrix

In [ ]:
np.mat([1,2,3,4])

In [ ]:
np.mat([[1,2],[1,2,3,4]])

# Deepcopy Vs Shallowcopy

In [ ]:
x=np.array([1,2,3])
x

In [ ]:
y=x   #y will also refer same location as x is pointing to=>changes in will reflect in y also

In [ ]:
y[1]

In [ ]:
x[1]

In [ ]:
y[1]=3  #changing y[1] here will reflect x[1]
y[1]

In [ ]:
x[1]

# np.copy() will create diff location but same data- DEEP COPY-DIFF Location

In [ ]:
x

In [ ]:
z=np.copy(x)
z

In [ ]:
x[0]=8  #x changed 
x

In [ ]:
z  #z didnt change even x changed

# numpy.fromfunction

In [ ]:
#Construct an array by executing a function over each coordinate.

In [ ]:
np.fromfunction(lambda i,j: i==j, (3,3), dtype=int)  #i==j is comparison func-comapring INDEXES gives T/F , Dimension=(3,3)

In [ ]:
np.fromfunction(lambda i,j: i*j, (3,3), dtype=int)  #indexes product

In [ ]:
np.fromfunction(lambda i,j,k: i*j*k, (3,3,3), dtype=int)  #indexes product

# Array-Dimension- 0 dim arr is scalar..no axis used...dim>=1 arr is vector ,using axis to represent

# 1-D array

In [ ]:
np.array([1,2,3])

# 2-D array

In [ ]:
np.fromfunction(lambda i,j: i==j, (3,3), dtype=int)

# 3-D array

In [ ]:
np.fromfunction(lambda i,j,k: i*j*k, (3,3,3), dtype=int)  #(3,3,3)=>means 3 arrays of 3X3 dimension

In [ ]:
np.fromfunction(lambda i,j,k,m: i*j*k*m, (4,3,3,3), dtype=int) #means 4 arrays of 3 -2D arrays of 3X3 dimensions

In [ ]:
np.array(np.random.randn(4,3,2))

In [ ]:
np.array(np.random.randn(4,3,2),ndmin=3)

In [ ]:
np.array(np.random.randn(2,4,3,2),ndmin=4)

In [ ]:
np.array(np.random.randn(2,4,3,2,2))  #total no. given in tuple is 5 which are 2,4,3,2,2. therefore 5-dimensions-5 brackets in start and end

# Create a new 1-dimensional array from an iterable object.

In [ ]:
iterable = (x*x for x in range(5))
iterable

In [ ]:
np.fromiter(iterable, float)

# A new 1-D array initialized from text data in a string

In [ ]:
a = np.fromstring('234 234',sep=' ')
a

In [ ]:
np.fromstring('1, 2', dtype=int, sep=',')

# How to create create a record array from a (flat) list of arrays

In [ ]:
x1=np.array([1,2,3,4])

In [ ]:
x2=np.array(['a','dd','xyz','12'])

In [ ]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

In [ ]:
r=np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')

In [ ]:
r

In [ ]:
r[1]["a"]

In [ ]:
r1=np.core.records.fromarrays([x1,x2,x3,x4])
r1

In [ ]:
r1[1]

In [ ]:
r1['f0']


In [ ]:
r1[1]['f0']

# Data types


# Important features of array

In [ ]:
arr = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(arr)
print("Type/Class of this object:",type(arr))
print("Here is the matrix\n----------\n",arr,"\n----------")
print("Dimension of this matrix: ",arr.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", arr.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", arr.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", arr.dtype,sep='') #dtype gives the data type contained in the array


In [ ]:
#if elements in an array is of int and float type then type() func  will upcast the array elements to float ..its takes more space than int

In [ ]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
mat.dtype

# Even tuples can be converted to ndarrays...

In [ ]:
b = np.array([(1.5,2,3), (4,5,6)])
b
#array made from tuples, not lists


In [ ]:
type(b)

# arange and linspace

# range function-Python core func- always consider integer dataset 


# arangefunction-numpy func-functionality same as range but definition diff                                - arange fun  consider float also
                            --ve jump can be given

In [ ]:
list(range(4,7))

In [ ]:
list(range(4,7,2))

In [ ]:
list(range(1.2,7,2))

In [ ]:
list(range(1,2.2,1))

In [ ]:
list(range(1,2,1.1))

In [ ]:
np.arange(1.1,2,1.1)

In [ ]:
np.arange(2,16,2)

In [ ]:
np.arange(8,2,-1)

# linspace

# jump is not here. ---no. of data between start and end points given

In [ ]:
np.linspace(1,4,20)

# Matrix creation

In [ ]:
np.zeros((2,3))  #(())-defined tuples

In [ ]:
np.ones(5)

In [ ]:
np.ones((1,2,3))

In [ ]:
np.ones((3,2,2))

In [ ]:
#Adding a no. in each array ele /any operation-sub/div/mul

In [ ]:
5+np.ones((2,4,5))

In [ ]:
np.empty((2,3))  #no such use--generate any random array

In [ ]:
m=np.eye(4)
m

In [ ]:
np.eye(2,3)

In [ ]:
np.eye(5)  #generally square array we create

In [ ]:
np.arange(3,7,2)

In [ ]:
np.linspace(2.0, 3.0, num=5)

In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

In [ ]:
np.linspace(2.0, 3.0, num=9, retstep=True)

In [ ]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

In [ ]:
np.logspace(2.0, 3.0, num=4,base = 10)

In [ ]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

In [ ]:
np.logspace(2.0, 3.0, num=4, base=2.0)

# Extract a diagonal or construct a diagonal array.

In [ ]:
import numpy as np
np.arange(8).shape

In [ ]:
#reshaping it-- total eles should be same as in shape like 8 in shape and reshape has=2*4=8 same


In [ ]:
np.arange(8).reshape(2,4)

In [ ]:
np.arange(8).reshape(2,2,2)

In [ ]:
np.arange(8).reshape(1,-1) #-1 denotes -shape to 1 * rest shape by default 1 is given then rest 8 will be by default

In [ ]:
np.arange(8).reshape(-1,4)

In [ ]:
np.arange(8).reshape(-169973930,-1)  #atleast given one dimesion

In [ ]:
np.arange(8).reshape(-130,2)

In [ ]:
np.arange(16).reshape(-1,4)

# Access diagonal elements

In [2]:
import numpy as np
x=np.arange(16).reshape(-1,4)
x


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
np.diag(x)   #diagonal ele of above array

array([ 0,  5, 10, 15])

In [4]:
#not square matrix/array

In [5]:
y=np.arange(16).reshape(2,8)
y
np.diag(y)            #returns first small sub matrix diagonal 

array([0, 9])

In [6]:
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [7]:
np.diag(y,k=0)

array([0, 9])

In [8]:
np.diag(y,k=1)

array([ 1, 10])

In [9]:
np.diag(y,k=2)

array([ 2, 11])

In [10]:
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

# -ve index for diagonal elements- see downwards to diagonal

In [19]:
import numpy as np

In [20]:
np.diag(y,k=-1)

array([8])

In [22]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
np.diag(x,k=-1)

array([ 4,  9, 14])

In [11]:
np.diag(x,k=-2)

array([ 8, 13])

In [12]:
np.diag(x,k=-3)

array([12])

In [13]:
np.diag(x,k=-4)

array([], dtype=int32)

In [14]:
np.diag(x,k=-5)

array([], dtype=int32)

# -ve ele in brackets==>col wise downwards diagonal

In [15]:
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [16]:
np.diag(y,k=-1)

array([8])

In [17]:
np.diag(y,k=-2)

array([], dtype=int32)

In [18]:
np.diag(y,k=-3)

array([], dtype=int32)

# func np.diag inside np.diag.will create new array with old diagonal eles and other eles will be 0


In [23]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

# Create a two-dimensional array with the flattened input as a diagonal. flattened - not nested

In [26]:
np.diagflat(([1,2],[3,4])) #by default k=0

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [41]:
np.diagflat(([1,2],[3,4]),k=2)

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [29]:
np.diagflat([1,2],1)  #here k=1

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

# An array with ones at and below the given diagonal and zeros elsewhere.-- triangle eles in the array

In [30]:
np.tri(3,5,1,dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [31]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

# #see the defintion 3X3 matrix and k=2 only there 1 and now check created array diagonalwill eb one and below also all will be one..
#therefor eevery where will be one


In [44]:
np.tri(3,3,2) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.tri(5,5,2)

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
#return a Lower triangle of an array.  np.tril (triangle lower)

In [36]:
np.tril([[1,2,3],[1,3,4],[1,4,5]],0)

array([[1, 0, 0],
       [1, 3, 0],
       [1, 4, 5]])

In [37]:
#upper triangle

In [38]:
np.triu([[1,2,3],[1,2,3],[1,2,3]],0)

array([[1, 2, 3],
       [0, 2, 3],
       [0, 0, 3]])

In [46]:
np.triu([[1,2,3],[1,2,3],[1,2,3]],k=-1)

array([[1, 2, 3],
       [1, 2, 3],
       [0, 2, 3]])

# Random number generation 

In [ ]:
rand-will generate random data for uniform distribution [0,1)]
Randn-will generate random data for NORMAL distribution mean=0, SD=1
randint-will generate random data for integer for given range by default will give 1 total no. of eles generated 


# #from numpy.random import randint as ri

In [47]:
#rand-Uniform distribution [0,1)
# 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

np.random.rand(2,3)

array([[0.99612967, 0.02661756, 0.3123195 ],
       [0.97555613, 0.46182299, 0.1580666 ]])

In [209]:
#randn- normal distribution
np.random.randn(4,3)

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 0.08550888  0.73651756  0.08329424]
 [ 0.75179279  0.42441618  0.47752353]
 [ 0.23835886  1.06582108 -0.01790105]
 [ 0.48190152 -0.24940656 -0.44992115]]


In [48]:
np.random.randint(1,10) #randint (low, high, # of samples to be drawn


6

In [49]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
np.random.randint(1,7,20) # 20 samples drawn from a dice throw

[[97 94 89 93]
 [60 91 40 45]
 [77 23 44 60]
 [98 86 25 31]]


array([5, 3, 4, 6, 6, 6, 2, 4, 2, 3, 4, 6, 5, 1, 4, 3, 5, 3, 1, 3])

# Reshaping

In [53]:
from numpy.random import randint as ri

In [57]:
a=ri(1,100,30)
a

array([40, 50, 48, 70, 29,  2, 14, 98, 77, 13, 58, 74, 78, 79, 60,  2, 22,
        1, 99, 12, 62, 35, 70, 82, 67, 11, 92, 68, 12, 83])

In [58]:
b=a.reshape(2,3,5)
b      

array([[[40, 50, 48, 70, 29],
        [ 2, 14, 98, 77, 13],
        [58, 74, 78, 79, 60]],

       [[ 2, 22,  1, 99, 12],
        [62, 35, 70, 82, 67],
        [11, 92, 68, 12, 83]]])

In [59]:
c=a.reshape(6,-5568)
c

array([[40, 50, 48, 70, 29],
       [ 2, 14, 98, 77, 13],
       [58, 74, 78, 79, 60],
       [ 2, 22,  1, 99, 12],
       [62, 35, 70, 82, 67],
       [11, 92, 68, 12, 83]])

In [61]:
A=ri(1,100,10)
A

array([98, 64, 90, 75, 86, 94, 27, 60, 72, 29])

# Sort
In 2ddata, we can sort row wise or col wise- axis=0 or 1 as aparameter
when axis=0==> means data movement while sorting will be row index wise
when axis=1==> means data movements while sorting will be col index wise

In [62]:
np.sort(A)

array([27, 29, 60, 64, 72, 75, 86, 90, 94, 98])

In [69]:
M=ri(1,100,25).reshape(5,5) #other way N=ri(1,100,(5,5))

M


array([[ 4, 51, 95, 23, 14],
       [12, 64, 53, 98, 79],
       [23, 80, 94, 47, 50],
       [95, 68, 76, 58, 47],
       [94, 22, 61,  6, 33]])

In [66]:
M.sort(M,axis=1, kind='quicksort')

TypeError: only integer scalar arrays can be converted to a scalar index

array([[86, 45,  4, 43, 55],
       [63, 34, 44, 26,  7],
       [ 2, 67, 50, 91, 16],
       [84, 88, 68, 49, 28],
       [79, 81, 72, 61, 74]])

# Max()

In [72]:
M

array([[ 4, 51, 95, 23, 14],
       [12, 64, 53, 98, 79],
       [23, 80, 94, 47, 50],
       [95, 68, 76, 58, 47],
       [94, 22, 61,  6, 33]])

In [70]:
M.max()

98

In [76]:
 #axis=1 colwise index will be use to find max one by one likesort() will be looklike we are doing rowwise..confusing()
M.max(axis=1)

array([95, 98, 94, 95, 94])

# argmax()-returns indxes of max value along axis=1

In [81]:
M.argmax() #with any given axis, by default it will give location of max ele

8

In [77]:
M.argmax(axis=1)

array([2, 3, 2, 0, 0], dtype=int64)

In [78]:
M.argmax(axis=0)

array([3, 2, 0, 1, 1], dtype=int64)

In [79]:
b

array([[[40, 50, 48, 70, 29],
        [ 2, 14, 98, 77, 13],
        [58, 74, 78, 79, 60]],

       [[ 2, 22,  1, 99, 12],
        [62, 35, 70, 82, 67],
        [11, 92, 68, 12, 83]]])

In [82]:
b.argmax()

18

# Doubt

In [83]:
b.argmax(axis=0)

array([[0, 0, 0, 1, 0],
       [1, 1, 0, 1, 1],
       [0, 1, 0, 0, 1]], dtype=int64)

# Indexing and Slicing

In [229]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [161]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [230]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


Elements from 3rd to 5th index are: [3 5]


In [231]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [233]:
print("Elements from last backwards are:", arr[-1:7:-1])


Elements from last backwards are: [10  9  8]


In [164]:
print("3 Elements from last backwards are:", arr[-1:-6:2])


3 Elements from last backwards are: []


In [165]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [64]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [84]:
import numpy as np
arr=np.array(ri(10,100,15)).reshape(3,5)
arr

array([[66, 92, 79, 37, 17],
       [87, 23, 99, 79, 19],
       [26, 41, 61, 46, 36]])

In [85]:
arr[1:4,3:5]

array([[79, 19],
       [46, 36]])

In [90]:
a=np.array(ri(10,100,45)).reshape(3,5,3)
a

array([[[58, 23, 27],
        [92, 39, 32],
        [55, 16, 27],
        [82, 59, 83],
        [98, 39, 38]],

       [[30, 66, 69],
        [96, 93, 58],
        [84, 51, 36],
        [77, 59, 90],
        [29, 81, 33]],

       [[71, 40, 82],
        [16, 86, 44],
        [73, 92, 97],
        [33, 40, 23],
        [95, 65, 81]]])

In [ ]:
#lets see we want to access [96, 93, 58]

In [91]:
a[1]

array([[30, 66, 69],
       [96, 93, 58],
       [84, 51, 36],
       [77, 59, 90],
       [29, 81, 33]])

In [93]:
a[1][1]

array([96, 93, 58])

In [94]:
#if we want to access 96
a[1][1][0]

96

# IMP-colwise extraction 

In [ ]:
#lets see we want to access first matrix 2nd col--colwise

In [102]:
a[0]

array([[58, 23, 27],
       [92, 39, 32],
       [55, 16, 27],
       [82, 59, 83],
       [98, 39, 38]])

In [ ]:
#now we want middle col (all rows middle col)

In [103]:
a[0][0:5,1:2]

array([[23],
       [39],
       [16],
       [59],
       [39]])

In [104]:
a[0][:,1] #or a[0][0:5,1:2]  ==> :=> all rows and 1 =>1th col

array([23, 39, 16, 59, 39])

In [105]:
a

array([[[58, 23, 27],
        [92, 39, 32],
        [55, 16, 27],
        [82, 59, 83],
        [98, 39, 38]],

       [[30, 66, 69],
        [96, 93, 58],
        [84, 51, 36],
        [77, 59, 90],
        [29, 81, 33]],

       [[71, 40, 82],
        [16, 86, 44],
        [73, 92, 97],
        [33, 40, 23],
        [95, 65, 81]]])

In [106]:
#now we want to access 2 tops rows from each matrix

In [107]:
a[0][:2]

array([[58, 23, 27],
       [92, 39, 32]])

In [109]:
a[:,:2]  #a[0:3,[0,1]]

array([[[58, 23, 27],
        [92, 39, 32]],

       [[30, 66, 69],
        [96, 93, 58]],

       [[71, 40, 82],
        [16, 86, 44]]])

# Subsetting- like putting some condition on matrix

In [110]:
a=np.array(ri(10,100,45)).reshape(3,5,3)
a

array([[[98, 74, 73],
        [15, 29, 10],
        [93, 67, 94],
        [29, 83, 87],
        [69, 93, 23]],

       [[81, 89, 45],
        [17, 39, 26],
        [20, 46, 51],
        [67, 61, 12],
        [52, 25, 26]],

       [[41, 47, 59],
        [71, 77, 94],
        [18, 36, 76],
        [58, 10, 47],
        [72, 81, 94]]])

In [111]:
a>50

array([[[ True,  True,  True],
        [False, False, False],
        [ True,  True,  True],
        [False,  True,  True],
        [ True,  True, False]],

       [[ True,  True, False],
        [False, False, False],
        [False, False,  True],
        [ True,  True, False],
        [ True, False, False]],

       [[False, False,  True],
        [ True,  True,  True],
        [False, False,  True],
        [ True, False, False],
        [ True,  True,  True]]])

In [113]:
a[a>50]

array([98, 74, 73, 93, 67, 94, 83, 87, 69, 93, 81, 89, 51, 67, 61, 52, 59,
       71, 77, 94, 76, 58, 72, 81, 94])

# Slicing

In [175]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [176]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [18]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [75]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [177]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)



Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [21]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[11 12]
 [21 22]]


In [178]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)



Change the sliced matrix
[[1000   12]
 [  21   22]]


In [22]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [115]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)



In [116]:
mat1

array([[8, 9, 6],
       [3, 4, 4],
       [8, 1, 2]])

In [117]:
mat2

array([[9, 7, 1],
       [1, 1, 7],
       [5, 7, 7]])

In [118]:
mat1*mat2  (its a just an indexwise multiplication- here reult is not matrix multiplication bcoz matric mul is mat1@mat2 )

array([[72, 63,  6],
       [ 3,  4, 28],
       [40,  7, 14]])

# matrix multiplication- condition- no. of comls in first matrix shld be = to no. rows of 2nd matrix

In [123]:
mat1@mat2

array([[111, 107, 113],
       [ 51,  53,  59],
       [ 83,  71,  29]])

In [119]:
mat1/0

<ipython-input-119-4a20909a461e>:1: RuntimeWarning: divide by zero encountered in true_divide
  mat1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [120]:
100+mat1

array([[108, 109, 106],
       [103, 104, 104],
       [108, 101, 102]])

In [121]:
mat1**3

array([[512, 729, 216],
       [ 27,  64,  64],
       [512,   1,   8]], dtype=int32)

In [122]:
pow(mat1,3)

array([[512, 729, 216],
       [ 27,  64,  64],
       [512,   1,   8]], dtype=int32)

# Broadcasting

In [174]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [254]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [256]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [257]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [262]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [263]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [264]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [265]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[9 5 4]
 [1 7 3]
 [8 3 5]]

2nd Matrix of random single-digit numbers
------------
 [[4 8 6]
 [7 6 8]
 [4 6 5]]


In [266]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[3.         2.23606798 2.        ]
 [1.         2.64575131 1.73205081]
 [2.82842712 1.73205081 2.23606798]]


In [267]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[8.10308393e+03 1.48413159e+02 5.45981500e+01]
 [2.71828183e+00 1.09663316e+03 2.00855369e+01]
 [2.98095799e+03 2.00855369e+01 1.48413159e+02]]


In [268]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.95424251 0.69897    0.60205999]
 [0.         0.84509804 0.47712125]
 [0.90308999 0.47712125 0.69897   ]]
[[9 5 4]
 [1 7 3]
 [8 3 5]]
[[4 8 6]
 [7 6 8]
 [4 6 5]]


In [270]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[1 5 4]
 [1 1 3]
 [0 3 0]]


array([[1, 5, 4],
       [1, 1, 3],
       [0, 3, 0]])

In [186]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [125]:
A = np.linspace(0,12*np.pi,1001)


In [126]:
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])